ID: 'VAE_0409_01_n1cls_nlb_kl601_chnl6_ep'

seed: 0

base:
  latent_chnl: 6
  epoch: 320
  if_pretrain: False
  if_test: True

#  if_pretrain: False # False or True
#  pretrained_model_path: null
#
#  # save step
#  model_save_step: 1
#  loss_save_step: 1
#  loss_set_save_step: 1
#  sample_save_step: 1
#
#  # save trian path
#  root_path: 'D:/Set_Practice/SD/KL_VAE_mian'
#  save_path: '/Ckpt/'
#  sample_save_pth: 'sample/'
#  model_save_path: 'weight/'
#  loss_save_path: 'loss/'
#
#  # save eval  path
#  model_eval_path: './'
#  model_eval_epoch_: 299
#  save_eval_path: './eval_Ckpt/'

  # log
  root_path: '/opt/data/private/fsy_QAQ_fsy/VAE_LDM/Ckpt_vae_new/'


  save_path: 'Dim_'
  sample_save_pth: 'sample/'
  model_save_path: 'weight/'
  loss_save_path: 'loss/'

  model_save_step: [0,20,40,60,80,100,120,140,160,180,200,220,240,260,280,300,320,340,360,380,400]
  loss_save_step: [0,20,40,60,80,100,120,140,160,180,200,220,240,260,280,300,320,340,360,380,400]
  loss_set_save_step: [0,20,40,60,80,100,120,140,160,180,200,220,240,260,280,300,320,340,360,380,400]
  sample_save_step: [0,20,40,60,80,100,120,140,160,180,200,220,240,260,280,300,320,340,360,380,400]

  opt_schl:
    base_lr: 1.0e-5
    min_lr: 5.0e-7
    T_max: 80
    weight_decay: null
    base_schl_step: [20,40,60,80,100,120,140,160,180,200,220,240,260,280,300,320,340,360,380,400]
    base_gamma: 0.9


model:
  loss_config:
    loss_choice: 2    # 0 vae with rec + kl + percep + g /1 disc with g/2 vae with rec + kl
    logvar_init: 0.0  # fixed

    kl_weight: 0.000001  # 1 10 100
    perceptual_weight: 0.0

    disc_start: null
    disc_num_layers: null
    disc_in_channels: null
    disc_factor: null
    disc_weight: null
    disc_conditional: null   # False
    disc_loss: null           # "hinge"
    use_actnorm: null         # False

  ENconfig:
    label: False
    num_labels: -1
    label_embed_dim: -1
    
    dims: 3
    double_z: True
    z_channels: 4
    
    resolution: 96
    in_channels: 1
    out_ch: 1
    ch: 64
    ch_mult: [ 1,2,4,8]  # num_down = len(ch_mult)-1  96/48/24/12/6
    
    use_checkpoint: False
    
    num_res_blocks: 1
    dropout: 0.0
    
    attn_resolutions: [ ]
    use_linear_attn: False   # default
    attn_type: 'none'         # default 'linear' 'basic'
    norm: True
    num_heads: 8
    dim_head: 64



data:
  data_cfg:
    if_train: True
    data_train_path: './DATA/VAE_DATA/AIMAX_all/mat_cls5_train/'
    data_eval_path: null
    type_label: 0
    label_path: null
    mat_key: 'BW'
    num_sample: 99999
    batch_size: 3
    batch_size_test: null

  data_cfg_test:
    if_train: False
    data_train_path: null
    data_test_path: './DATA/VAE_DATA/AIMAX_all/mat_cls5_test/'
    type_label: 0
    label_path: null
    mat_key: 'BW'
    num_sample: 99999
    batch_size: null
    batch_size_test: 1


# ID: '24112612_labeled_ep'     # FFT oneshaot super resulution/ def get_last_layer(self)  waiting for setting
# # seed: 66
# base:
#   if_pretrain: False # False or True
#   pretrained_model_path: null
#   embed_dim: 6
#   epoch: 200

#   # save step
#   model_save_step: 15
#   loss_save_step: 30
#   loss_set_save_step: 30
#   sample_save_step: 15

#   # save trian path
#   root_path: '.'
#   save_path: '/Ckpt/'
#   sample_save_pth: 'sample/'
#   model_save_path: 'weight/'
#   loss_save_path: 'loss/'

#   # save eval  path
#   model_eval_path: './////////'
#   model_eval_epoch_: 99999999
#   save_eval_path: './eval_Ckpt////////'


# model:
#   patience_opt: False
#   opt_schl:
#     base_learning_rate: 2.0e-5
#     base_schl_step: 20
#     base_gamma: 0.8
#     patience_gamma: 0.8
#     patience_threshold: 300
#     base_patience_step: 20

# #  disc_opt_schl:
# #    disc_learning_rate:
# #    disc_schl_step:
# #    disc_patience_step:
# #    disc_gamma:

#   embed_dim: 6

#   lossconfig:
#     loss_choice: 2    # 0 vae with rec + kl + percep + g /1 disc with g/2 vae with rec + kl
#     logvar_init: 0.0  # fixed

#     kl_weight: 1    # 10/1/0.1/0.001/0.00001
#     perceptual_weight: 0.0

#     disc_start: null
#     disc_num_layers: null
#     disc_in_channels: null
#     disc_factor: null
#     disc_weight: null
#     disc_conditional: null   # False
#     disc_loss: null           # "hinge"
#     use_actnorm: null         # False

#   ddconfig:
#     label: True
#     num_labels: 6
#     label_embed_dim: 32
#     double_z: True
#     z_channels: 6
#     resolution: 96
#     in_channels: 1
#     out_ch: 1
#     ch: 64
#     ch_mult: [ 1,2,4,]  # num_down = len(ch_mult)-1
#     num_res_blocks: 1
#     attn_resolutions: [ ]
#     dropout: 0.0
#     use_linear_attn: False   # default
#     attn_type: basic         # default



# data:
#   if_train: 'train'  #  fixed 'eval'
#   data_train_path: '/opt/data/private/KL_VAE/KL_VAE_mian/KLVAE/data/to_resize_96_class_allin/'
#   data_eval_path: '/opt/data/private/KL_VAE/KL_VAE_mian//KLVAE/data/to_resize_96_class_test_allin/'
#   label_path: ''
#   mat_key: 'BW'
#   num_sample: 685
#   batch_size: 1
#   in_channle: 1
#   resoltion: 96
#   total_dim: 5    # len([batch,1,192,192,192])
#   if_label : 2    # 1descriptor 2 class  0 None
